name = "blue-src"
main = "src/index.js"
compatibility_date = "2025-04-11"

# Optional, but good practice
workers_dev = false

routes = [
  { pattern = "blue.inz.com.ar/*", zone_id = "60b6e1db95acb7603e6fb6dd8b2648e3" }
]

# You can find your zone_id and account_id in the Cloudflare dashboard
account_id = "c20d3bd18424c5b076930cb7fd0a9d57"
